# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        # Install Azure Functions Core Tools
    - name: Install Azure Functions Core Tools
      run: |
        curl -sL https://aka.ms/install-artifacts-credprovider.sh | bash
        npm i -g azure-functions-core-tools@3 --unsafe-perm true
    # Install Dapr CLI
    - name: Install Dapr CLI
      run: |
        wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
        dapr --version
    # Initialize Dapr
    - name: Initialize Dapr
      run: dapr init
    #- name: UnitTests
     # run: dotnet test ./test/UnitTests --no-restore --verbosity normal
    #- name: InfrastructureTests
     # run: dotnet test ./test/Test.Infrastructure --no-restore --verbosity normal
    #- name: ConfigurationTests
     # run: dotnet test ./test/Microsoft.Tye.Extensions.Configuration.Tests --no-restore --verbosity normal
    - name: E2ETests
      run: dotnet test ./test/E2ETest --no-restore --verbosity normal    
